### ISSUE TITLE
Numpy 2.0 Compatibility

### ISSUE THREAD

**Issue by minerharry** [mverleg/pyjson_tricks#105]
Not compatible with numpy 2.0; import fails with `ValueError: numpy.dtype size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject`

**Comment by claydugo** [comment]
Can you try to make a more reproducible minimal example?

**Comment by mverleg** [comment]
Thanks for reporting! I agree that an example would be great.

From the error message I can't say where it goes wrong; it might have to do with b64 array storage? But the [tests for that](https://github/mverleg/pyjson_tricks/blob/ac5c8bea5e78315a1036738baeab5bbe631f1794/tests/test_np.py#L250-L250) are passing for numpy `2.1.3`.

**Comment by minerharry** [comment]
Interesting, sorry I really thought it’d be a simple reproducible version incompatibility. I’ll post reproduction details in a sec when I get back to my computer

**Comment by minerharry** [comment]
Tried making a new conda environment and couldn't reproduce. A further look at the stack trace shows it's actually a pandas issue; update pandas fixed the issue. False alarm!

**Comment by mverleg** [comment]
Thanks for reporting and following up, glad it works
