### ISSUE TITLE
Handle encoding for numpy array scalars

### ISSUE THREAD

**Issue by rldotai** [mverleg/pyjson_tricks#18]
The `json_tricks` library will serialize instances of `numpy.ndarray` but if you pass it an array scalar (e.g., a single element of an array, which have datatypes like `numpy.int64`, `numpy.float64`, etc.)

For example:

```python
>>> z = np.array([1,2,3])  
>>> json_tricks.dumps(z)
'{"dtype": "int64", "shape": [3], "__ndarray__": [1, 2, 3]}'
>>> json_tricks.dumps(z[0])
TypeError: Object of type <class 'numpy.int64'> could not be encoded by TricksEncoder using encoders [<function json_date_time_encode at 0x7f38028fea60>, <function class_instance_encode at 0x7f38028febf8>, <function json_complex_encode at 0x7f38028fec80>, <function numpy_encode at 0x7f3802410400>]
```

My present workaround is to ensure that all array scalars are converted to numpy arrays before attempting to serialize (`json_tricks.dumps(np.array(z[0]))` in the above) but it would be easier if this was handled automatically.

**Comment by mverleg** [comment]
Good find, thanks for reporting!

I suppose they should be serialized in a special way, not as python scalars or numpy `(1,)` arrays.

There's a problem though, in Python 2, `float64` is a subclass of `integer`, so Python just encodes it without ever reaching custom encoders. The same for `float64` and `float`. This is not the case for other types like int32, and is also not the case for Python 3. This could lead to very confusing behaviour...

**Comment by mverleg** [comment]
Correction, it seems to happen for Python 3 as well in my test. But the difference between float32 and float64 (for example) will be hard to solve.

**Comment by mverleg** [comment]
I'm afraid storing the type consistently (for all numpy scalar types) is not possible without extreme amounts of hacking around the standard implementation. In Python 3 it might be possible with dynamically swapping `__instancecheck__` (also pretty hacky), but that's not available in Python 2.

Encoding only the types that don't overlap with Python types seems very inconsistent and will probably lead to bugs for users.

So I think the "best" (least bad) course of action is to encode all numpy types as the closest Python type. This means that if you serialize a Numpy `float32`, you'll get back a Python `float`.

I'll add it as an experimental feature for now, feedback is welcome.

**Comment by mverleg** [comment]
A function `encode_scalars_inplace` has been added that you can use if you want to encode numpy scalars with the correct type. You'll have to call this first and then `dump` the result, which will load correctly. It's not very elegant of performant (since it goes through the whole data structure again), but it's the best that can be done.

**Comment by mverleg** [comment]
If you're okay with serializing as python scalars, that functionality is available in v3.5+ (already on pip). It might change in the future if a better way becomes available...

**Comment by rldotai** [comment]
Conversion (with or without a warning) plus the option to convert then encode if necessary is probably the best solution.
In my case it was type coercion that lead to the presence of array scalars in the data.
I cannot think of a case where having the exact numpy scalar types would be relevant when encoding to JSON, since JSON already entails a certain amount of coercion on its own (tuples become lists, etc.).

I've tested the new version on the code I'm working with and have found no issues thus far.
I'll have an opportunity to test with more aggressive serialization/deserialization tomorrow.

As an aside, thanks for being so responsive, and for addressing this issue in such a satisfactory manner. 
This library has probably saved me at least a full day's work implementing my own serialization scheme.

**Comment by mverleg** [comment]
Some improvement may be possible with the `parse_float` and `parse_int` flags as in issue #21

**Comment by mverleg** [comment]
I don't see this being possible anytime soon as long as this uses the standard json library, so I'm going to close it.
