### ISSUE TITLE
Add support for Decimal type

### ISSUE THREAD

**Issue by rgreinho** [mverleg/pyjson_tricks#21]
Decimals are not supported, but it would be a nice addition:
``` python
>> import json_tricks.nonp as json
>>> from decimal import *
>>> d = Decimal(1) / Decimal(7)
>>> d
Decimal('0.1428571428571428571428571429')
>>> json.dumps(d)
Traceback (most recent call last):
  File "<input>", line 1, in <module>
    json.dumps(d)
  File "/Users/regreinh/.virtualenvs/jsontricks/lib/python3.6/site-packages/json_tricks/nonp.py", line 79, in dumps
    string = cls(sort_keys=sort_keys, obj_encoders=encoders, **jsonkwargs).encode(obj)
  File "/usr/local/Cellar/python3/3.6.0/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/Cellar/python3/3.6.0/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/Users/regreinh/.virtualenvs/jsontricks/lib/python3.6/site-packages/json_tricks/encoders.py", line 54, in default
    type(obj), self.__class__.__name__, ', '.join(str(encoder) for encoder in self.obj_encoders)))
TypeError: Object of type <class 'decimal.Decimal'> could not be encoded by TricksEncoder using encoders [<function json_date_time_encode at 0x101e79d90>, <function class_instance_encode at 0x101f2ad08
>, <function json_complex_encode at 0x101f2ad90>, <function json_set_encode at 0x101f2ae18>, <function nonumpy_encode at 0x101fbf510>]
>>>
```

**Comment by mverleg** [comment]
Hmm ok, how do you propose they should be serialized?

**Comment by mverleg** [comment]
Like many other types that this package can serialize, I'm conflicted whether restoring it should restore a Decimal, but I think it should.

* Storing it as a decimal-specific type would make the encoding something like `{"__decimal__": ...}` which might be annoying for people reading this without `json-tricks`.
* Storing it as a float (`3.141592653589793115997963468544185161590576171875`) would be easy for others to read, but would change the type when restored (with `json-tricks`).

I think the first option is better. Maybe one day I should add an optional flag to serialize things as close to primary types as possible.

**Comment by rgreinho** [comment]
I like the first option better I think. 

Also, maybe you could align with the behavior of SimpleJson (https://simplejson.github.io/simplejson/), where they have the `parse_float=decimal.Decimal` for the `loads` function, and `use_decimal=True` for the `dumps` function.

**Comment by mverleg** [comment]
I'm not sure we can have a `parse_float` option. When dealing with numpy scalars (#18), I found that no hooks are called for primary types (which some numpy types are in some versions of Python). That was serialization and this is deserialization though, so I'll have a look.

As for the encoding of decimals, I think it could be

    {"__decimal__": "3.141592653589793115997963468544185161590576171875"}
    {"__decimal__": "-Infinity"}

pity about the strings but likely inevitable. For fractions one of these:

    {"__fraction__": [1, 3]}
    {"__fraction__": true, "numerator": 1, "denominator": 3}

**Comment by rgreinho** [comment]
It looks great!

**Comment by mverleg** [comment]
Well what do you know, there *is* a `parse_float`, which should already work. It's a valid argument for the Python json library, so the argument should be passed on if you provide it to `json-tricks`.

    >>> loads('[1, 3.14]', parse_int=lambda s: int('7' + s), parse_float=lambda s: float('5' + s))
    [71, 53.14]

Seems the problem is only with serialization. Which is fine in this case, since `Decimal` is not a subclass of `float`.

**Comment by mverleg** [comment]
I've make a quick implementation. Tomorrow I'll add tests, write documentation and release it on pypi.

**Comment by rgreinho** [comment]
Wooow! Thank you so much for implementing it so fast!

**Comment by mverleg** [comment]
Everything seems to work, thanks for reporting
