### ISSUE TITLE
Support pandas dataframes

### ISSUE THREAD

**Issue by mverleg** [mverleg/pyjson_tricks#26]
Of course optionally, similar to numpy arrays.

There are several [formats](http://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.to_json.html), though I feel that column-based vectors would make most sense...

**Comment by mverleg** [comment]
Actually let's keep it open, there may be bugs, or more details that need serialization

**Comment by mverleg** [comment]
Needs documentation

**Comment by Jenselme** [comment]
> Actually let's keep it open, there may be bugs,

I think I found one. I have pandas installed but no pandas dataframes in a serialized JSON with json-tricks. When I deserialize my JSON I get errors like:
```
~/Seafile/Exchange/tests-serialization/json_tricks/decoders.py in pandas_hook(dct)
    179 
--> 180         if '__pandas_dataframe__' in dct or '__pandas_series__' in dct:
    181                 # todo: this is experimental
    182                 if not getattr(pandas_hook, '_warned', False):

TypeError: argument of type 'ColorEnum' is not iterable
```

I think that this comes from the fact that unlike in other decoders, you don't check whether `dct` is a dict before trying to process it.

**Comment by mverleg** [comment]
That sounds like a likely explanation yes!

**Comment by mverleg** [comment]
I think the problem was indeed that there was no check, which only comes to light when using a custom  hook (because otherwise pandas is the first hook and always gets dicts). Good find!

**Comment by Jenselme** [comment]
Thanks for the correction, it now works as expected! Since I don't use pandas, I can't test the serialization/deserialiation part.

**Comment by mverleg** [comment]
Seems things are working, I'm going to close.
