### ISSUE TITLE
Add support for <type 'time.struct_time'>

### ISSUE THREAD

**Issue by Miserlou** [mverleg/pyjson_tricks#31]
I was hoping that this library would be able to automatically serialize <type 'time.struct_time'> (Python 9-tuples) into something like RFC 2822. It doesn't yet, but it could! :)

**Comment by mverleg** [comment]
Well, I implemented the whole thing only to find out that ``struct_time`` is an instance of ``tuple`` and therefore cannot have non-standard serialization. Similar to decimal (#21) and numpy scalars (#18), except there's no ``parse_tuples`` flag as far as I can tell...

It's possible to do a solution similar to numpy scalars, having a separate function which replaces ``struct_time`` instances by primitives before encoding. Or they could be encoded as is, and there could be an option (not default) to decode any length-9 list of integers as ``struct_time``.

[Here's a patch](https://gist.github.com/mverleg/087111f0b03d99b7c85f5072f0392acc) that might've worked if tuples could have custom encoders. In case you want to adapt it.

On a side note... ``struct_time`` seems like a bad way to handle time, with no timezones and several redundant and possibly inconsistent fields. It seems useful for communicating with other languages, but the format isn't the same as most other languages which use C convention (week starts on Sunday, months start at 0...). Any reason not to just use datetimes?

**Comment by Miserlou** [comment]
Wow, thank you for your swift reply and efforts towards this!

Honestly, I have no love for this format, but it is used by an older library that I'm using. I don't know why Python keeps it around. I ended up writing my own custom serializer.

**Comment by mverleg** [comment]
Okay, there's an implementation in the patch. Maybe after #17 we can get around the restriction with primitives and it'll be implemented, but I'll close it for now.
