### ISSUE TITLE
Include JSONDecodeError in json_tricks module

### ISSUE THREAD

**Issue by skewty** [mverleg/pyjson_tricks#32]
Could you please include the standard JSONDecodeError class in the json_tricks package as a convenience?
I often find myself having to import that class from the standard json module.

**Comment by mverleg** [comment]
Sounds good, but I won't have the opportunity for the next two weeks, sorry. After that!

**Comment by mverleg** [comment]
It turns out that only recent versions of Python 3 use this error (as does simplejson). Older versions use ValueError, of which JSONDecodeError is a subclass. For convenience, it'll be imported if it's available, but I'd recommend using ValueError for portability.

**Comment by mverleg** [comment]
Forgot to close this
