### ISSUE TITLE
Enum support by default

### ISSUE THREAD

**Issue by Jenselme** [mverleg/pyjson_tricks#34]
Hi,

Since Python 3.4 we can create enum natively with the `enum` package. This feature is also available with [enum34](https://pypi.org/project/enum34/) for previous versions of python. I think this can be useful to include enum support directly in json-tricks.

Since I had to write an implementation for that today, I'll gladely contribute if you want.

**Comment by mverleg** [comment]
I had apparently missed that bit of news, it seems like a good addition.
I'd be interested in seeing the implementation, thanks! (Does it work with arbitrary enum values?)

**Comment by Jenselme** [comment]
Great! I am working on it. It should work on arbitrary enum values. I encountred problem with serialization of `IntEnum` under Python 2. I hope I'll be able to open a PR tomorow.

**Comment by mverleg** [comment]
Thanks for the pull request, it looks good!

A few things I'm not totally sure about:

* What should be encoded with ``primitives=True``? I feel maybe it should be/include the enum option's name...
* Should the value be exported? It's not necessary for loading by ``pyjson-tricks``, but maybe for humans or in other contexts?
* If we ever find a way to properly encode primitives, we can apply it to IntEnum, so I'll add a label.

**Comment by mverleg** [comment]
I fixed one small bug and credited you in the README, I think it's ready for release. Thanks for your effort!

**Comment by Jenselme** [comment]
Thanks for the quick merge.

Concerning the encoding of the enums as primitives, I think it is a bit tricky. I chose to encode the value instead of the name because it more, in my opinion, it matches the chosen primitive type. What I mean by that is: the values will most likely be strings or ints depending on what the user chose. By encoding the value, I think we are more closely respecting this decision.

On the other hand however, encoding the value makes it harder to rebuild the enum in some cases. For insance, with this enum:
```python
class MyEnum:
    member = 'hello'
```

I can use `MyEnum['member']` (ie the name of the member) to access the member, but I cannot do `MyEnum['hello']` to access it. I need to loop on all the values of the enum. Maybe I was influenced by how I manage enums: I always encode the property like `MEMBER = 'MEMBER'` so the name is equal to the value.

So maybe that in the context of `json-tricks` it makes more sense to encode the name instead of the value.

**Comment by mverleg** [comment]
Although I imagine it's rather rare, it's allowed to have two options with the same value, while names are always unique.

I'm currently thinking it may be better to include both, since there's no clear winner:

    {"member": "hello"}

**Comment by Jenselme** [comment]
> Although I imagine it's rather rare, it's allowed to have two options with the same value, while names are always unique.

Indeed. So yes, it may be better to include them both in a dict like you just proposed.

**Comment by mverleg** [comment]
They now have names and values, and it's available on pip!
