### ISSUE TITLE
Invalid datetime decoding

### ISSUE THREAD

**Issue by DeadMor0z** [mverleg/pyjson_tricks#41]
Do not use tzinfo in datetime/time constuctor with pytz. This will produce datetime/time objects with incorrect timezone in most cases (from pytz documentation):

> Unfortunately using the tzinfo argument of the standard datetime constructors ”does not work” with pytz for many timezones.
> 
> \>>> datetime(2002, 10, 27, 12, 0, 0, tzinfo=amsterdam).strftime(fmt)
> '2002-10-27 12:00:00 LMT+0020'
> It is safe for timezones without daylight saving transitions though, such as UTC:
> 
> \>>> datetime(2002, 10, 27, 12, 0, 0, tzinfo=pytz.utc).strftime(fmt)
> '2002-10-27 12:00:00 UTC+0000'

so, the proper way of constructing datetime/time objects with timezone is to create naive object, then use localize method of pytz timezone class. like this:

`>>> amsterdam.localize(datetime(2002, 10, 27, 12, 0, 0)).strftime(fmt)`
`'2002-10-27 12:00:00 CET+0100'`

**Comment by mverleg** [comment]
Hmm that's pretty crappy from ``pytz``, thanks for catching that, I would probably not have found that any time soon!

**Comment by mverleg** [comment]
I've created a fix, including a test that should prevent the issue from coming back.

I think the problem only affects datetimes (not times, dates or timedeltas), right?

If anyone could do (and leave) a quick review, that's be great!

**Comment by mverleg** [comment]
New version is online!
