### ISSUE TITLE
Add 3.11.3 release tag

### ISSUE THREAD

**Issue by cfobel** [mverleg/pyjson_tricks#43]
While the version number was [updated to 3.11.3][3.11.3] (as of a04e342c462528bf40c6e4926bb938c27dbe2a0b), there was no corresponding tag added so it doesn't show up in the [list of releases][releases].

[3.11.3]: https://github.com/mverleg/pyjson_tricks/commit/a04e342c462528bf40c6e4926bb938c27dbe2a0b
[releases]: https://github.com/mverleg/pyjson_tricks/releases

**Comment by mverleg** [comment]
I didn't rely on the tags much, but since they can be useful, I added a commit hook that creates the tags automatically so they'll stay in sync f66cf2eca2ecd5cd65e19b743e56aaf40ca9e556

I also added v3.11.3, thanks for reporting.
