### ISSUE TITLE
Ignoring errors during complex object encoding

### ISSUE THREAD

**Issue by tdorsey** [mverleg/pyjson_tricks#44]
I'm serializing a complex object that has several children that I can safely ignore (RLocks, XMLElements, etc). I don't need these objects to serialize, but I do need the rest of the encoding to continue.

Prior to using silence_typeerrors on the default encoder, it fails on the Rlock below:

Traceback (most recent call last):
  File "test.py", line 10, in <module>
    json = jt.dumps(s, silence_typeerror=True)
  File "/usr/local/lib/python3.6/site-packages/json_tricks/nonp.py", line 90, in dumps
    primitives=primitives, **jsonkwargs).encode(obj)
  File "/usr/local/lib/python3.6/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python3.6/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/local/lib/python3.6/site-packages/json_tricks/encoders.py", line 58, in default
    type(obj), self.__class__.__name__, ', '.join(str(encoder) for encoder in self.obj_encoders)))
TypeError: Object of type <class '_thread.RLock'> could not be encoded by TricksEncoder using encoders [<function nopandas_encode at 0x7fc9f798cd90>, <function nonumpy_encode at 0x7fc9f798cea0>, <function enum_instance_encode at 0x7fc9f798c8c8>, <function json_date_time_encode at 0x7fc9f79c26a8>, <function json_complex_encode at 0x7fc9f798ca60>, <function json_set_encode at 0x7fc9f798cb70>, <function numeric_types_encode at 0x7fc9f798cae8>, <function class_instance_encode at 0x7fc9f798c9d8>]

After passing silence_typeerrors kwargs, it gets past the RLock, but fails on an XMLElement with a TypeError.

Traceback (most recent call last):
  File "test.py", line 12, in <module>
    json = jt.dumps(s, kwargs)
  File "/usr/local/lib/python3.6/site-packages/json_tricks/nonp.py", line 90, in dumps
    primitives=primitives, **jsonkwargs).encode(obj)
  File "/usr/local/lib/python3.6/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python3.6/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/local/lib/python3.6/site-packages/json_tricks/encoders.py", line 58, in default
    type(obj), self.__class__.__name__, ', '.join(str(encoder) for encoder in self.obj_encoders)))
TypeError: Object of type <class 'xml.etree.ElementTree.Element'> could not be encoded by TricksEncoder using encoders [<function nopandas_encode at 0x7f95faba0d90>, <function nonumpy_encode at 0x7f95faba0ea0>, <function enum_instance_encode at 0x7f95faba08c8>, <function json_date_time_encode at 0x7f95fabd76a8>, <function json_complex_encode at 0x7f95faba0a60>, <function json_set_encode at 0x7f95faba0b70>, <function numeric_types_encode at 0x7f95faba0ae8>, <function class_instance_encode at 0x7f95faba09d8>]

Is there another way to ignore unserializable objects, or am I using something incorrectly?

**Comment by mverleg** [comment]
There's not a way to totally skip it, maybe that'd be a good addition.

But it's already easy to replace the unencodable objects by null or some other value:

    from json_tricks.nonp import DEFAULT_ENCODERS
    dumps(your_data, obj_encoders=DEFAULT_ENCODERS + [lambda obj: "(unknown)"])

or

    dumps(your_data, extra_obj_encoders=[lambda obj: None])

Is that useful?

(So what it does is add an extra encoder after existing ones, which will replace anything not handled yet by a specific object).

(Don't use `obj_encoders` with this trick because that comes before the standard encoders, losing specials like numpy array encoding).

**Comment by tdorsey** [comment]
Thanks for the help! 

That's an improvement in that it no longer throws, but still not the behavior I'd expect. The whole object is returned as null, since the lambda appears to be handling the entire object. A minimal example:

# samplecred.py
```python
import threading
class SampleCredentials:
        def __init__(self, user, password):
                self.user = user
                self.password = password
                self.lock = threading.RLock()
```
# test.py
``` python
import json_tricks as  jt
from json_tricks.nonp import DEFAULT_ENCODERS
from samplecred import SampleCredentials

c = SampleCredentials("johndoe", "abc123")

json = jt.dumps(c.lock, extra_obj_encoders=[lambda RLock: None])
print(json)

json2 = jt.dumps(c, obj_encoders=DEFAULT_ENCODERS + [lambda RLock: None])
print(json2)

```

json/json2 are both None, but I'd expect to see something along the lines of 
``` json
 { "user: "johndoe", "password": "abc123", "lock": None }
```
Is this possible?

**Comment by mverleg** [comment]
I've added a less hacky way that seems to work better:

	from json_tricks import dumps, fallback_ignore_unknown
	from json_tricks.np import DEFAULT_ENCODERS
	from functools import partial
	import threading
	
	class SampleCredentials:
		def __init__(self, user, password):
			self.user = user
			self.password = password
			self.lock = threading.RLock()
	
	c = SampleCredentials("johndoe", "abc123")
	json2 = dumps(c, fallback_encoders=[
		partial(fallback_ignore_unknown, fallback_value='(unknown type)')])
	print(json2)

**Comment by mverleg** [comment]
Version `3.12.0` is now on pip!

**Comment by mverleg** [comment]
Thanks for reporting the problem!

The second problem seems like it is an object with a custom `__new__`, which unfortunately isn't supported (#16).

The first one looks like it might be a bug, I'll try to look into it!

**Comment by mverleg** [comment]
My suspicion about why it fails is that it needs to encode a lambda, apparently in PoolManager (there is one in the `__init__`). Unfortunately that's not possible. I've improved the error message though.

**Comment by mverleg** [comment]
Based on my comments from 2 years ago, this is solved to the extend it can be solved, right?

I'm going to close it, feel free to re-open if a problem persist that can be solved.
