### ISSUE TITLE
Create conda recipe to distribute on conda-forge

### ISSUE THREAD

**Issue by jhkennedy** [mverleg/pyjson_tricks#49]
I'm using JSON tricks (v13.11.0) in [LIVVkit](https://github.com/LIVVkit/LIVVkit) and would like to distribute LIVVkit via conda-forge. 

However, my [build recipe](https://github.com/conda-forge/staged-recipes/pull/6176) is failing because [conda-forge requires all dependencies to be in conda-forge](https://conda-forge.org/docs/recipe.html#avoid-dependencies-outside-of-conda-forge). Therefore, I'd like to build a conda-forge recipe for JSON tricks (for at least version 13.11.0). 

@mverleg, would you mind if I created a conda-forge recipe? 

I'm happy to volunteer as the maintainer of the conda-forge recipe and I can do it: 

1. out of a branch from my [LIVVkit/staged-recipes](https://github.com/LIVVkit/staged-recipes) fork, or 
2. you could fork [conda-forge/staged-recipes](https://github.com/conda-forge/staged-recipes) and I can contribute/help there.

I assume you'd want to be listed as a [maintainer](https://conda-forge.org/docs/recipe.html#maintainer-role) as well in the recipe? *Note: this will create some spam for you.*

**Comment by jhkennedy** [comment]
I also should mention, it likely doesn't matter where the initial recipe is created; once accepted, there will be a conda "feedstock" repository will be created for the JSON tricks recipe [here](https://conda-forge.org/feedstocks) and the recipe will be maintained there.

**Comment by mverleg** [comment]
Thanks for helping make json-tricks accessible. I don't know much about Conda (or livv), so I'd say go ahead with option 1, if you can be the maintainer that'd be great :+1:

**Comment by jhkennedy** [comment]
Thanks @mverleg ! 

I've got a the process going for 13.11.0 with PR conda-forge/staged-recipes#6220

Once the feedstock repo is going, I'll update it for the latest version(s) of ``json_tricks.`` 

I'll ping you from there if I need any help. Closing.
