### ISSUE TITLE
Pandas DeprecationWarning: .ix is deprecated

### ISSUE THREAD

**Issue by mverleg** [mverleg/pyjson_tricks#55]

**Comment by erwanp** [comment]
With the latest Pandas 1.0.0 version, `ix` was removed and therefore the DeprecationWarning now leads to an Error, which renders `json_tricks` unusable.

In my case it happens in:
```
/json_tricks/encoders.py:319: in pandas_encode

    repr[name] = tuple(obj.ix[:, k].values)
```

**Comment by mverleg** [comment]
Thanks! New patch release 3.13.6 created
