### ISSUE TITLE
Please a __version__ variable to __init__.py

### ISSUE THREAD

**Issue by hmaarrfk** [mverleg/pyjson_tricks#58]
Versioneer for python exists to make this easy to use with github/pypi automated releases.

https://github.com/warner/python-versioneer

Thanks for considering.

**Comment by smarie** [comment]
An alternative that I like and recommend is to use `setuptools_scm`.

This is how you make it work: https://smarie.github.io/python-getversion/#package-versioning-best-practices. (note that the `getversion` library where this recommendation is hosted, is not used in the pattern - it is only useful when a library *doesn't* have a __version__ attribute)

**Comment by hmaarrfk** [comment]
Right. I am using pkg resources which I guess is the same thing.


Thanks for considering.

This stuff is a moving target, and there isn't always a good reason to change.  

Feel free to close

**Comment by smarie** [comment]
> I am using pkg resources which I guess is the same thing.

No, `getversion` is a bit more complete - it relies on several strategies, `pkg resources` is only one of them but is a bit limited as it does not cover all cases (unzipped wheels, project sources added to python path by your IDE such as PyCharm, etc.). But this is another discussion :) 

For the present ticket I agree with you that *something* should be done so that `__version__` is set. Let's wait for maintainer's feedback then. Thanks for the discussion !

**Comment by hmaarrfk** [comment]
getversion does work in the problematic use cases i've had where `pip` detects the version at install time, but for dependencies that I am depeveloping, that often goes out of sync at run time.

 Not sure if I want to depend on it just yet. 
`0.2.3+31.g8cafa99`, but seems cool.

Either case, I sympathesize with the maintainer not wanting to have to keep track of two numbers, one in `setup..py` and the other in `__init__.py`.

**Comment by mverleg** [comment]
Hmm doesn't it seem a bit unnecessary to add a dependency for something that is just a few lines of code?

It's probably a good idea to add this though, I can see how it would be useful since there is already logic depending on `sys.version_info` in this project.

**Comment by hmaarrfk** [comment]
Are you referring to versioneer?

**Comment by mverleg** [comment]
By the dependencies I mean both (this was my quick impression, maybe I'm wrong). With a few lines I mean adding the version in a text file and reading that.

Currently any changes are blocked by #60 though...

**Comment by hmaarrfk** [comment]
Depends how much of burden you see in changing those two lines. I hate it. I just want to tag and move on.

**Comment by mverleg** [comment]
From v3.13.2 it works for me and for the automated test
