### ISSUE TITLE
Serializing NaN

### ISSUE THREAD

**Issue by skjerns** [mverleg/pyjson_tricks#70]
Even though it's stated in the README that it works, I have trouble saving an array with `nan` in it:

```Python
import json_tricks
json_tricks.dumps(np.empty(3) * np.nan)
# ValueError: Out of range float values are not JSON compliant
```

any idea how to fix that?

using v3.14.0 and Python 3.7

**Comment by skjerns** [comment]
my bad. option `allow_nan` is right in front of me.

**Comment by mverleg** [comment]
There was also some confusion in #63, I'll add to the readme then. Do note that it's not standard json so might not work when sent to other programs (might even be [dangerous](https://stackoverflow.com/questions/1423081/json-left-out-infinity-and-nan-json-status-in-ecmascript) if javascript uses `eval` to parse it, but they shouldn't).
