### ISSUE TITLE
Pandas ix is deprecated since pd.__version__ > 1.0

### ISSUE THREAD

**Issue by Laksh1997** [mverleg/pyjson_tricks#71]
```
  File "/opt/conda/lib/python3.6/site-packages/json_tricks/encoders.py", line 319, in pandas_encode
    repr[name] = tuple(obj.ix[:, k].values)
```

Got this error when trying to serialize a df.

**Comment by mverleg** [comment]
@Laksh1997 Thanks for reporting! Could you make sure you have version 3.13.6 or higher of json-tricks, and check if the problem persists?
