### ISSUE TITLE
TypeError in Python 3.9 due to removal of encoding kwarg from json.loads

### ISSUE THREAD

**Issue by dschreij** [mverleg/pyjson_tricks#80]
In Python 3.9, the `encoding` kwarg of `json.loads` is removed, see https://docs.python.org/dev/whatsnew/3.9.html#removed:

> The encoding parameter of json.loads() has been removed. As of Python 3.1, it was deprecated and ignored; using it has emitted a DeprecationWarning since Python 3.8. (Contributed by Inada Naoki in bpo-39377)

This causes json_tricks to crash when calling these functions with a type error, for instance:

```python
  ...
  File "/Users/daniel/miniconda3/envs/os3.3-py39/lib/python3.9/site-packages/json_tricks/nonp.py", line 266, in load
    return loads(string, preserve_order=preserve_order, ignore_comments=ignore_comments, decompression=decompression,
  File "/Users/daniel/miniconda3/envs/os3.3-py39/lib/python3.9/site-packages/json_tricks/nonp.py", line 236, in loads
    return json_loads(string, object_pairs_hook=hook, **jsonkwargs)
  File "/Users/daniel/miniconda3/envs/os3.3-py39/lib/python3.9/json/__init__.py", line 359, in loads
    return cls(**kw).decode(s)
TypeError: __init__() got an unexpected keyword argument 'encoding'
```

**Comment by mverleg** [comment]
Interesting, thanks for reporting. It seems it'd be easy to remove for python3 if it does nothing, though I like to keep python2 working when it's not too hard...

**Comment by mverleg** [comment]
Hmm I'm having a look and I think this argument is only passed through **kwargs, is that right?

I'm afraid there's not much I can do about it then (I could silently drop it from kwargs, but that's probably more confusing than just giving an error).

I guess the solution is to check calling code and make sure encoding isn't passed to json-tricks anywhere.

**Comment by mverleg** [comment]
Added 3.9 to tests and setup.py in v3.15.5

**Comment by dschreij** [comment]
Hmmm that may be the case. This is a third-party library that uses json_tricks, so I don't really know exactly how it invocates it. I will have to look into this, but if it is the case, this issue can of course be closed. Thanks for your efforts!

**Comment by mverleg** [comment]
Feel free to reopen if there's something we can do
