### ISSUE TITLE
Add support for encoding/decoding bytestrings

### ISSUE THREAD

**Issue by mcdevitts** [mverleg/pyjson_tricks#81]
I have been using json_tricks for years now, and it's been very handy - especially with numpy. I recently realized that python's native bytestrings cannot be natively serialized in json. It would be very handy to include a __bytes__ type if possible. I implemented my own version, and the hook / encode methods are listed below.

I would be happy to fold this into json_tricks if there's a desire.

```python
def json_bytes_hook(dct: Any) -> bytes:
    """Return an encoded complex number to it's python representation.

    Parameters
    ----------
    dct : Any

    Returns
    -------
    value : bytes
    """
    if not isinstance(dct, dict):
        return dct
    if "__bytes__" not in dct:
        return dct
    parts = dct["__bytes__"]
    assert isinstance(parts, str)
    return parts.encode()


def json_bytes_encode(obj: Any, primitives: bool = False) -> Dict:
    """Encode a complex number as a json dictionary of it's real and imaginary part.

    Parameters
    ----------
    obj : Any
    primitives : bool

    Returns
    -------
    dict
        json primitives representation of `obj`

    """
    if isinstance(obj, bytes):
        if primitives:
            return obj.decode("utf8").split("\0", 1)[0]
        else:
            return hashodict(__bytes__=obj.decode("utf8").split("\0", 1)[0])
    return obj
```

**Comment by mverleg** [comment]
Thanks for the suggestion, sorry it took so long.

If I understand correctly, this encodes the bytes as utf8, right? Aren't there byte sequences that are not valid utf8?

**Comment by mcdevitts** [comment]
That's a great point. Another solution could be to encode the bytestring
using the printable representation.

**Comment by mverleg** [comment]
Version 3.16.0 is released with bytes support for Python 3.

Python 2 does not encode bytes because it does not have a bytes type (and is dead).

Let me know if you run into any problems.
