### ISSUE TITLE
Test failures on s390x (big endian) architecture

### ISSUE THREAD

**Issue by cboltz** [mverleg/pyjson_tricks#86]
When building on s390x (aka "Mainframe"), there are several test failures that are caused by the different byte order (big endian on s390x, little endian on x86_64).

For example, test_encode_compact_inline_compression fails with

```
[  241s]     def test_encode_compact_inline_compression():
[  241s]     	data = [array([[1.0, 2.0, 3.0, 4.0], [5.0, 6.0, 7.0, 8.0], [9.0, 10.0, 11.0, 12.0], [13.0, 14.0, 15.0, 16.0]])]
[  241s]     	json = dumps(data, compression=False, properties={'ndarray_compact': True})
[  241s]     	assert 'b64.gz:' in json, 'If the overall file is not compressed and there are significant savings, then do inline gzip compression.'
[  241s] >   	assert json == '[{"__ndarray__": "b64.gz:H4sIAAAAAAAC/2NgAIEP9gwQ4AChOKC0AJQWgdISUFoGSitAaSUorQKl1aC0BpTWgtI6UFoPShs4AABmfqWAgAAAAA==", "dtype": "float64", "shape": [4, 4], "Corder": true}]'
[  241s] E    assert '[{"__ndarray...rder": true}]' == '[{"__ndarray...rder": true}]'
[  241s] E      - [{"__ndarray__": "b64.gz:H4sIAAAAAAAC/2NgAIEP9gwQ4AChOKC0AJQWgdISUFoGSitAaSUorQKl1aC0BpTWgtI6UFoPShs4AABmfqWAgAAAAA==", "dtype": "float64", "shape": [4, 4], "Corder": true}]
[  241s] E      + [{"__ndarray__": "b64.gz:H4sIAAAAAAAC/7P/wAAGDgxQmgNKC0BpESgtAaVloLQClFaC0ipQWg1Ka0BpLSitA6X1oLQBhAYAVFOzqoAAAAA=", "dtype": "float64", "shape": [4, 4], "Corder": true}]
[  241s] 
[  241s] tests/test_np.py:264: AssertionError
```

If you base64-decode and gunzip the two values and do a hexdump, you get the following diff:

```
--- b64.gz:H4sIAAAAAAAC/2NgAIEP9gwQ4AChOKC0AJQWgdISUFoGSitAaSUorQKl1aC0BpTWgtI6UFoPShs4AABmfqWAgAAAAA==
+++ b64.gz:H4sIAAAAAAAC/7P/wAAGDgxQmgNKC0BpESgtAaVloLQClFaC0ipQWg1Ka0BpLSitA6X1oLQBhAYAVFOzqoAAAAA=
@@ -1,9 +1,9 @@
+00000000  3f f0 00 00 00 00 00 00  40 00 00 00 00 00 00 00  |?.......@.......|
-00000000  00 00 00 00 00 00 f0 3f  00 00 00 00 00 00 00 40  |.......?.......@|
           ^^ ^^             ^^ ^^  ^^                   ^^
+00000010  40 08 00 00 00 00 00 00  40 10 00 00 00 00 00 00  |@.......@.......|
-00000010  00 00 00 00 00 00 08 40  00 00 00 00 00 00 10 40  |.......@.......@|
           ^^ ^^             ^^ ^^  ^^ ^^             ^^ ^^
+00000020  40 14 00 00 00 00 00 00  40 18 00 00 00 00 00 00  |@.......@.......|
-00000020  00 00 00 00 00 00 14 40  00 00 00 00 00 00 18 40  |.......@.......@|
           ^^ ^^             ^^ ^^  ^^ ^^             ^^ ^^
+00000030  40 1c 00 00 00 00 00 00  40 20 00 00 00 00 00 00  |@.......@ ......|
-00000030  00 00 00 00 00 00 1c 40  00 00 00 00 00 00 20 40  |.......@...... @|
           ^^ ^^             ^^ ^^  ^^ ^^             ^^ ^^
+00000040  40 22 00 00 00 00 00 00  40 24 00 00 00 00 00 00  |@"......@$......|
-00000040  00 00 00 00 00 00 22 40  00 00 00 00 00 00 24 40  |......"@......$@|
           ^^ ^^             ^^ ^^  ^^ ^^             ^^ ^^
+00000050  40 26 00 00 00 00 00 00  40 28 00 00 00 00 00 00  |@&......@(......|
-00000050  00 00 00 00 00 00 26 40  00 00 00 00 00 00 28 40  |......&@......(@|
           ^^ ^^             ^^ ^^  ^^ ^^             ^^ ^^
+00000060  40 2a 00 00 00 00 00 00  40 2c 00 00 00 00 00 00  |@*......@,......|
-00000060  00 00 00 00 00 00 2a 40  00 00 00 00 00 00 2c 40  |......*@......,@|
           ^^ ^^             ^^ ^^  ^^ ^^             ^^ ^^
+00000070  40 2e 00 00 00 00 00 00  40 30 00 00 00 00 00 00  |@.......@0......|
-00000070  00 00 00 00 00 00 2e 40  00 00 00 00 00 00 30 40  |.......@......0@|
           ^^ ^^             ^^ ^^  ^^ ^^             ^^ ^^
```
As you can see, the byte order in each block of 8 bytes is reversed. I didn't check in detail, but I assume the test expects a specific value in little endian encoding (like done on x86_64), but gets it big endian-encoded on s390x.

There are more failing tests, likely also caused by similar issues. See https://build.opensuse.org/package/live_build_log/openSUSE:Factory:zSystems/python-json_tricks/standard/s390x for the full log.

**Comment by mverleg** [comment]
Good catch thanks, sounds reasonable. I don't have big endian systems but I added the endian to the data explicitly, so I hope that solves it for newly stored data.

Would you be interested in checking out the latest master and trying it on the mainframe?

**Comment by cboltz** [comment]
Thanks, that sounds good :-)

I have to admit that I don't use pyjson_tricks myself, I "only" noticed the failures in the testsuite during the package build. However, I can offer to run the testsuite with the updated code on a mainframe VM.

As an alternative, you can get a mainframe VM yourself for free:
* a VM that expires after 120 days: https://developer.ibm.com/articles/get-started-with-ibm-linuxone/ (which will lead you to https://linuxone.cloud.marist.edu/#/register?flag=VM).
* a permanently available VM for open source projects: https://www.ibm.com/community/z/open-source/virtual-machines-request/

**Comment by mverleg** [comment]
Thanks for the hint! I currently get

> Service is temporarily not available.

I'll just go ahead and release the new version

**Comment by cboltz** [comment]
Hmm, someone gave a talk at DevConf.cz today where the test VMs were announced in one of the slides. I wonder if this talk was too successful ;-)
Maybe try again in a few days...

That said - thanks for the new release! It makes things much better, but a few issues remain on s390x. See #88 for details.
