### ISSUE TITLE
Add an alternative, smaller storage for numpy arrays

### ISSUE THREAD

**Issue by mverleg** [mverleg/pyjson_tricks#9]
Some notes:
1. Would be ideal if it is extensible to other 'raw' data (like images).
2. Using more than one save file would be a disadvantage as it's easy to lose parts.
3. Mixing formats in the same file (e.g. json followed by raw binary) might be difficult for humans and other implementations to read.
4. Base64 encoding loses efficiency (33% and not great for zipping) - or [base85](http://stackoverflow.com/a/1443240/723090), which may be worse.
5. Using a python specific format (like .[npz](http://stackoverflow.com/questions/4090080/what-is-the-way-data-is-stored-in-npy)) would be disadvantage.
6. Reading and writing efficiency is important (reading is already really slow).

I can't think of a way that satisfies all these preferences, so I'll leave it open for now.

**Comment by mverleg** [comment]
Discussion about the topic: http://stackoverflow.com/questions/1443158/binary-data-in-json-string-something-better-than-base64

**Comment by mverleg** [comment]
So for clarity: this would be an addition and not replace the default in the foreseeable future.

**Comment by mverleg** [comment]
Here is a benchmark for the current model (separately for raw and gzipped) against many other methods: https://github.com/mverleg/array_storage_benchmark

![](https://raw.githubusercontent.com/mverleg/array_storage_benchmark/master/result/bm_random.png)

So it competes with CSV but loses to anything closer to binary. Maybe we should store arrays as PNG? :-)

**Comment by mverleg** [comment]
I'm tending towards putting each array in a binary file with a simple header (same as current metadata).

I'd prefer a similar standardized format but I can't find one, and this'd be just a few lines of code in any language. Also, it can be easily deduced by looking at the binary file, without knowing where it's from.

These files would then all be packaged together into one lightly compressed archive.

I just haven't figured out how to gracefully handle the file extension, which should be filename.tar.gz where it'd normally be filename.json (if there are no binary arrays).

**Comment by mverleg** [comment]
If a smaller storage version is added, I might also change the default separators to remote whitespace.

**Comment by erwanp** [comment]
Hello @mverleg . I wandered if you still had some development plan here? In our application we use json_tricks because the output format is human readable, but in some cases we only want performance! Would be amazing if the same library could provide both options.

**Comment by mverleg** [comment]
I'm not sure, I've personally stored some large arrays as numpy dumps linked to from json, but I am not sure that's a viable solution for json-tricks because it's not really json anymore...

I have also considered base64 encoded data (possibly gzipped first), which would save a lot over the current solution, but not be as good as binary. It'd be valid, self-contained json though.

Also not sure how best to pass options to individual encoders/decoders.

**Comment by mverleg** [comment]
It seems to mostly work, you can test the branch `binary_ndarray` if you want.

It's much smaller than normal json, but only a bit smaller when gzipped (~20%). It's substantially faster to dump though (with or without gzip)

But load is only about twice as fast, and more than twice as slow as dump. I might investigate that a bit more before releasing.

**Comment by mverleg** [comment]
Turns out it's because of comment parsing, which will have to be picked up separately #74

(I recommend using `ignore_comments=False` when dealing with big files without comments)

**Comment by mverleg** [comment]
Fix released in v3.15.0

**Comment by erwanp** [comment]
Thank you for these improvements!!
